# Build Docker image for this app using Azure Pipelines
# http://docs.microsoft.com/azure/devops/pipelines/languages/docker?view=vsts
trigger:
  - develop

pr: none

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'discover-uni-widget:$(Build.BuildId)'
  dockerId: devdiscoverunicontainerregistry

steps:
  - script: |
      sed -i 's/{{domain_name}}/'$domainName'/g' ./public/widget.js
      sed -i 's/{{api_domain}}/'$apiHost'/g' ./public/widget.js
      sed -i 's/{{api_key}}/'$apiKey'/g' ./public/widget.js
    env:
      domainName: $(rootDomain)
      apiHost: $(apiHostName)
      apiKey: $(apiHostKey)
    displayName: 'Adding env variables'

  - script: |
      pushd '$(projectRoot)'
      docker build -f ./Dockerfile -t $(dockerId).azurecr.io/$(imageName) .
      docker login -u $(dockerId) -p $pswd $(dockerId).azurecr.io
      docker push $(dockerId).azurecr.io/$(imageName)
    env:
      pswd: $(dockerPassword)
    displayName: 'Build and push Docker image to Dev'
