# Build Docker image for this app using Azure Pipelines
# http://docs.microsoft.com/azure/devops/pipelines/languages/docker?view=vsts
trigger:
  - release/*

pr: none

pool:
  vmImage: 'Ubuntu-latest'

variables:
  imageName: 'discover-uni-widget:$(Build.BuildId)'
  dockerId: preproddiscoverunicontainerregistry
  nodeVersion: '20.x'

steps:

  - task: UseNode@1
    inputs:
      version: '$(nodeVersion)'
    displayName: 'Use Node.js $(nodeVersion)'

  - script: |
      sed -i 's|{{domain_name}}|'$domainName'|g' ./public/widget.js
      sed -i 's|{{api_domain}}|'$apiHost'|g' ./public/widget.js
      sed -i 's|{{api_key}}|'$apiKey'|g' ./public/widget.js
      cssStyles=$(<./public/widget.css)
      cssStyles=${cssStyles//[$'\t\r\n']}
      sed -i 's|{{styles}}|'"$cssStyles"'|g' ./public/widget.js
    env:
      domainName: $(rootDomain)
      apiHost: $(apiHostName)
      apiKey: $(apiHostKey)
    displayName: 'Adding env variables'

  - script: |
      pushd '$(projectRoot)'
      docker build -f ./Dockerfile -t $(dockerId).azurecr.io/$(imageName) .
      docker login -u $(dockerId) -p $pswd $(dockerId).azurecr.io
      docker push $(dockerId).azurecr.io/$(imageName)
    env:
      pswd: $(dockerPassword)
    displayName: 'Build and push Docker image to Pre Prod'

